travis:
  secure:
    BINSTAR_TOKEN: j6Za6vq60vu534BKi7GU6jdL5S5Azauvpz8W8UDU/8T60Ba5vWEXU0a2yShsMIlMt54BeTjykvuqUN9O+zbP+rxYlMXRdcZh8sYl4vpWeVRXSdl6sYnS7zAGZmSsMv6PoN0E1h/IgCaWsuLQBNQXFoW/GQ4APtsxEOF6MIxHCBpadf6wUKwtamCVhPdtynNoYl1h/Ik3oJ8F9FMRrHR4xwFBUQnQTkDIDaYaXicN0sH66Ml0BhgmWl6F7YM8dWJSTwnNBs3V3t4cvG2hkYA8uUtJJPATa6N9udL4Odpq84VXgyczGlSTFVBCDfg6CxlvTGoxvHcLA2fLQa3YdBLr9X8CZ0i9BO060M/798XmF63uQL70uEXGIjwsQw1hszqeo8+2CSJ/PLrFQn3zRi8gLvHPk6yySbu2T9PEl8gxK/vKmQwB0bWeykL+QkirSLVYgYIpB/fkvS8JDZb2PhBY1JOd5LZJtwiIV8SlZdi1qQ695fuiQPBrN0tYmGVbDeYI5tHIrH5MViqg8mfBIEYMFv7o6IID4iGjQiyC0iOe84SXJkVBx4fPxIfdRma2cCcIKQwOqq04+wwmsOW9LpkPyAOfnr/Ugfwi72l+C8WARiyt1idv6TwT0GDIz86d9Tpbw0ohYMGxlKUGWH0xR5jchEDs+CABoWkYkdIgUHubaBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
