travis:
  secure:
    BINSTAR_TOKEN: VFAZJBc5oq6BXW/KtJPi+SkaVqyL5XwJPJ6LsvxdVbYbL+OcNMZ8Tkj4RyuyRpkC/1qXTGCMTAg44Wu0dfP8DV7lfEvgQ/81aSXVB22VqaTnnzYVqaBIodggivR2Lj60DaV4ez441JIe3AdRNbslyz+p7VYdrsF4IuyZ2rmxskl+iUz3kIWK8MM/TgQUaBHKb6p4UjEcOmkyN63YBafVk0h+oKVvmHc+cSnSadGIEIFZpRfTXeF9a8Lwyyjk4PVZZAM8L3eXQDzJ9SEPAc4B2Sns+btXCLfHQRs5XsJll7IW2ZPhOhOffk8bNOa1oFJ4k86SUVeP/aEIw23tgPRcqUsSbF2rO+BOYEACqZoFi1hIc/NyLaolHHuTj3jvlKVZnNKcm8hmHS63JGTwie5OVRq+w2J73z12FKuW/zx9wRXJR/DAgeKxZURbNHbCAkv8Ruf72ZZ8YvUYvEYAsAO4lU6DuONkW/Fpzor4lA0YQtgTXz8xRDKqymIYUarnbCjCN79OtWso8EJcGpZk9d6RGh97PHzKDCv6tuUUdxAUszehHC9+uOc7IY9/QrPIAUhhsM3iZi9joZleqLcou7ZZMQ5BA8+bICtbSAJSjxHdSoBwhvZidkdZpYW/kKJfSL9zQliHxwCaOHntorc49wq7jArO716aEJ6EleeEKNFw5uI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
